### ISSUE TITLE
Need a clearer way to finish drawing

### ISSUE THREAD

**Issue by davidheyman** [axismaps/levant-carta-next#35]
We need a more obvious way to tell users how to finish a drawing. Maybe an additional button? Otherwise a clear call-to-action to (click the original point to finish drawing) would be helpful as well as a highlight and a large target on the first vertex would help.

**Comment by DaviTeodoro** [comment]
I showed it to a friend and he was confused when using it. Perhaps, it is a good idea to revisit this issue, so I`m reopen it.

**Comment by bcsheesley** [comment]
I think this is on the right track. I like the popup that tells the user to click again to finish. In addition, would a persistent visual cue help to indicate that the point is special/different, like a dot or halo? Clicking point 1 or 3 would close the polygon. Just a thought.

![Poly-3](https://user-images.githubusercontent.com/4501388/140775881-5d9238a3-cdba-444b-998f-5c23bf017ec7.png)

![Poly-3 – 1](https://user-images.githubusercontent.com/4501388/140777423-a1d3f575-254f-467f-80e7-a5ef77a3046b.png)
