### ISSUE TITLE
Time Filter (Not displaying features within the range correctly)

### ISSUE THREAD

**Issue by Uilvim** [axismaps/levant-carta-next#68]
Filtering by Year does not show features that should be within the chosen time range. This usually happens when the date picked is the same as either the firstyear or lastyear of a feature
![timefilter_issue16_BEFORE](https://user-images.githubusercontent.com/45857022/153888069-23a81caf-0431-4e53-aa1a-0d250d968ca9.JPG)
![timefilter_issue16_AFTER](https://user-images.githubusercontent.com/45857022/153888074-b047b5a6-bd28-4f5e-ad80-5fb65af938e9.png)
.

**Comment by DaviTeodoro** [comment]
@davidheyman I'm not sure how to fix it in the client. I checked the request and it is correctly sending the inserted values to the backend, but no feature is returned. 
<img width="899" alt="Screen Shot 2022-02-21 at 14 07 33" src="https://user-images.githubusercontent.com/11483241/155000127-7bc66757-d8b7-4539-84db-0c8f8495fb34.png">

**Comment by davidheyman** [comment]
Update time selection function to correctly operate on the range:

```
F_FirstYear >= T_FirstYear and F_FirstYear <= T_LastYear
OR
F_LastYear >= T_FirstYear and F_LastYear <= T_LastYear
```
