### ISSUE TITLE
Basemap and Overlay Raster option

### ISSUE THREAD

**Issue by Uilvim** [axismaps/levant-carta-next#71]
Currently it is only possible to change the overlay Raster. It is necessary to have an option to change both basemap and the overlay raster. So, not only you can compare maps with the basemap but also maps with others maps.

**Comment by davidheyman** [comment]
@DaviTeodoro Let's add a custom dropdown to the map area that allows you to choose between the 2 options. If you put it in and then assign it to me, I can clean up the design.

**Comment by DaviTeodoro** [comment]
@davidheyman here it is https://github.com/axismaps/levant-carta-next/commit/e0c3c1e959de2be6fb490828b81c2763a3ee6365. I added a simple button that triggers a menu, see what you think. Feel free to reopen the issue if you think something needs to change.
<img width="425" alt="Screen Shot 2022-03-08 at 15 48 16" src="https://user-images.githubusercontent.com/11483241/157304975-d0322e37-0ab2-4dd2-9bc8-cdce04433289.png">
