### ISSUE TITLE
De-activating and re-activating the window causes full layer reload

### ISSUE THREAD

**Issue by Ualas** [axismaps/levant-carta-next#76]
When adding a Layer (E.g. BuildingsPoly) to the map, It constantly reloads the data disrupting the app's usability.
![Capture (2)](https://user-images.githubusercontent.com/9088402/174155486-7aacf313-fe2a-4a36-a1e4-ab5ccd5c7d7a.PNG)

**Comment by davidheyman** [comment]
Switch to a different tab then come back to the editor window and there is a full reload of the loaded layer.

**Comment by davidheyman** [comment]
This might be a can't / won't fix due to a limitation of the library, which is fine. The rendering delay in the new version isn't too bad at all.
